import type { Metadata } from 'next'
import { Noto_Serif_Bengali } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'

const NotoSerifBengali = Noto_Serif_Bengali({
  subsets: ['latin', 'bengali'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      data-theme='white'
      className={`${NotoSerifBengali.className}  h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <Toaster position='top-right' richColors />
        <main>{children}</main>
      </body>
    </html>
  )
}
